### ISSUE TITLE
Random Shuffeln bzw Random Integer Listen

### ISSUE THREAD

**Issue by isigoing** [ob-fun-ws18/studienarbeit-bugproducer#1]
Da ich die Random Integer Liste nicht wirklich hinbekommen habe, habe ich mir gedacht, ich kann ja auch einfach die Liste mit meinen Nachbarn mischen und dann einfach den ersten Wert nehmen, was auch funktionieren würde, jedoch treffe ich hierbei natürlich auf das gleiche Problem.

Ich versteh nicht wirklich, wenn ich meine Liste mit folgender Funktion shuffle:
https://github.com/ob-fun-ws18/studienarbeit-bugproducer/blob/823415c7ef13861dfadc639401cc3f268ee88315/src/Lib.hs#L128-L132

erhalte ich anschließend eine Liste vom Typ "IO [Field]", jedoch weiß ich nicht wirklich wie ich ab hier weiter verfahren kann, schließlich brauche ich nur eine [Field] Liste.

Im unteren Auszug habe ich dies getestet.
https://github.com/ob-fun-ws18/studienarbeit-bugproducer/blob/823415c7ef13861dfadc639401cc3f268ee88315/src/Lib.hs#L137-L148

Die Funtionen zur Random Integer List existieren auch noch in der Main, falls dies doch der besser weg wäre.

Ich hoffe Sie können mir hier weiterhelfen.

**Comment by obcode** [comment]
Sie müssen das Shuffeln als IO-Action ausführen, z.B.

```Haskell
startGame :: IO ()
startGame = do
    putStrLn "*** Game started ***"
    print mat
    print neighbours
    shuff <- shuffle neighbours
    print shuff
    where
        empty = generateEmptyMatrix 4 4
        start = setStartPoint empty (1,1)
        mat = getMatrix start
        field = getField start
        neighbours = calcNeighbours mat (getPosition field)
        -- shuff = shuffle neighbours
```

HTH

**Comment by isigoing** [comment]
Es hat auf jedenfall geholfen, stehe aber jetzt vor einem anderen Problem. Werde am Montag nochmal auf Sie zu kommen.

**Comment by obcode** [comment]
Alles klar, sonst gerne auch per Issue.
