### ISSUE TITLE
Kurze Frage zu kommendem Montag

### ISSUE THREAD

**Issue by isigoing** [ob-fun-ws18/studienarbeit-bugproducer#2]
Und zwar sollen ja am kommenden Montag die Präsentationen stattfinden, jedoch kann anschließend noch am Projekt weitergearbeitet werden, oder? Die Finale Abgabe ist ja erst am 28.01.
Und wann soll dann das Release 1 erstellt werden, zur Präsentation oder wenn man wirklich fertig ist?

**Comment by obcode** [comment]
14.01.2019
Abschlusspräsentation der Studienarbeit (== Release 1) im Rahmen der Lehrveranstaltung.
28.01.2019, 08:00 Uhr
Deadline für endgültige Abgabe. Das letzte Release vor dem 28.01.2019, 08:00 Uhr ist
automatisch die Abgabe.

**Comment by isigoing** [comment]
Hab es auch gerade auf dem Blatt zur Studienarbeit gefunden. Dennoch Vielen Dank für Ihre Antwort. Muss wohl leider erst etwas blind gewesen sein. Sorry!

**Comment by obcode** [comment]
Kein Problem. Lieber einmal zu oft fragen...
